### ISSUE TITLE
extract_encoder.py run fail

### ISSUE THREAD

**Issue by Cyc-striving** [MaitySubhajit/SelfDocSeg#5]
Traceback (most recent call last):
  File "/root/autodl-tmp/SelfDocSeg/pretraining/extract_encoder.py", line 633, in <module>
    resnet_seq.load_state_dict(wts)                                                     # loading weights to the new encoder
  File "/root/miniconda3/envs/selfdocseg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:

**Comment by MaitySubhajit** [comment]
Please include the complete stack trace, so that we understand the issue clearly.
